-   repo: https://github.com/pre-commit/pre-commit
    rev: master
    hooks:
    -   id: validate_manifest
-   repo: local
    hooks:
    # Below code is a copy from pre-commit-hooks.yaml
    - id: gitlab-ci-linter
      name: .gitlab-ci.yml linter
      description: Validates .gitlab-ci.yml file (pure-python version)
      entry: gitlab-ci-linter
      language: python
      language_version: python3
      pass_filenames: false
      files: .gitlab-ci.yml
