---
# Copy below code to .pre-commit-config.yaml on update
- id: gitlab-ci-linter
  name: .gitlab-ci.yml linter
  description: Validates .gitlab-ci.yml file (pure-python version without dependencies)
  entry: gitlab-ci-linter
  language: python
  language_version: python3
  pass_filenames: false
  files: .gitlab-ci.yml
